const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["assets/vendor-CbspLdtO.js","assets/vendor-CS74yUSC.css"])))=>i.map(i=>d[i]);
import{i as f,a as y,b as L}from"./assets/vendor-CbspLdtO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const I="modulepreload",X=function(e){return"/busy-status/"+e},h={},O=function(n,i,o){let t=Promise.resolve();if(i&&i.length>0){document.getElementsByTagName("link");const s=document.querySelector("meta[property=csp-nonce]"),a=(s==null?void 0:s.nonce)||(s==null?void 0:s.getAttribute("nonce"));t=Promise.allSettled(i.map(l=>{if(l=X(l),l in h)return;h[l]=!0;const m=l.endsWith(".css"),q=m?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${l}"]${q}`))return;const c=document.createElement("link");if(c.rel=m?"stylesheet":I,m||(c.as="script"),c.crossOrigin="",c.href=l,a&&c.setAttribute("nonce",a),document.head.appendChild(c),m)return new Promise((S,P)=>{c.addEventListener("load",S),c.addEventListener("error",()=>P(new Error(`Unable to preload CSS for ${l}`)))})}))}function r(s){const a=new Event("vite:preloadError",{cancelable:!0});if(a.payload=s,window.dispatchEvent(a),!a.defaultPrevented)throw s}return t.then(s=>{for(const a of s||[])a.status==="rejected"&&r(a.reason);return n().catch(r)})};function C(e){e?f(e,{initialCountry:"auto",loadUtils:()=>O(()=>import("./assets/vendor-CbspLdtO.js").then(n=>n.u),__vite__mapDeps([0,1]))}):console.error("Елемент #phone не знайдено.")}const $="https://jsonplaceholder.typicode.com/posts",p=[{question:"Question 1",options:["option 1","option 2","option 3"]},{question:"Question 2",options:["option 1","option 2","option 3"]},{question:"Question 3",options:["option 1","option 2","option 3"]},{question:"Question 4",options:["option 1","option 2","option 3"]},{question:"Question 5",options:["option 1","option 2","option 3"]}];function x(e){y.success({position:"center",theme:"dark",messageColor:"green",message:e,progressBarColor:"green",transitionIn:"fadeIn",transitionOut:"fadeOut",timeout:3e3})}function u(e){y.error({position:"topRight",theme:"dark",messageColor:"red",message:e,progressBarColor:"red",transitionIn:"fadeIn",transitionOut:"fadeOut",timeout:5e3})}let d=0,g=[];function v(){const e=document.getElementById("quiz"),i=p[d].options.map((t,r)=>`
        <li data-value="${t}">
          ${t}
        </li>
      `).join("");e.innerHTML=`
    <h2>${p[d].question}</h2>
    <ul class="options">
      ${i}
    </ul>
  `;const o=e.querySelectorAll(".options li");o.forEach(t=>{t.addEventListener("click",()=>{o.forEach(r=>r.classList.remove("selected")),t.classList.add("selected"),A()})}),N()}function A(){const e=document.querySelector(".options li.selected");e?(g.push(e.dataset.value),d++,d<p.length?v():(document.getElementById("quiz-container").style.display="none",document.getElementById("registration-container").style.display="block")):u("Please, choose an option")}function B(){return g}function N(){const e=document.getElementById("progress");e&&(e.innerHTML=`<span style="color: black;">${d+1}</span><span style="color: rgb(68, 67, 67);">/${p.length}</span>`)}async function T(e){return L.post($,e,{headers:{"Content-Type":"application/json"}})}function E(e){return/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(e)}function b(e){return f.getInstance(e).isValidNumber()}function w(e){return e.trim()?/^[A-Za-zА-Яа-яІіЇїЄєҐґ'’\-]+$/.test(e.trim())?e.trim().length<2||e.trim().length>50?"Name must be between 2 and 50 characters":null:"Name can only contain letters and special characters like apostrophes or dashes":"Please, write your name"}function z(e,n){const i=e.querySelector("#name"),o=e.querySelector(".wt-email-input"),t=w(i.value);return t?(u(t),!1):E(o.value.trim())?!n||!b(n)?(u("Please, enter a phone number in the correct format, such as +380XXXXXXXXX!"),!1):!0:(u("Please, write a correct email (e.g., example@domain.com)"),!1)}function Q(e,n){const i=e.querySelector("#name"),o=e.querySelector(".wt-email-input");i.addEventListener("blur",()=>{const t=w(i.value);t&&u(t)}),o.addEventListener("blur",()=>{E(o.value.trim())||u("Please, write a correct email (e.g., example@domain.com)")}),n.addEventListener("blur",()=>{b(n)||u("Please, enter a phone number in the correct format, such as +380XXXXXXXXX!")})}document.addEventListener("DOMContentLoaded",()=>{v(),C(document.querySelector(".wt-phone-input"));const e=document.querySelector(".wt-form"),n=document.querySelector(".wt-phone-input");Q(e,n),e.addEventListener("submit",async i=>{var s,a;i.preventDefault();const o=document.getElementById("submitButton");if(o&&(o.disabled=!0,o.textContent="Sending..."),!z(e,n)){o&&(o.disabled=!1,o.textContent="Send");return}const t=f.getInstance(n).getNumber(),r={name:e.querySelector("#name").value,email:e.querySelector(".wt-email-input").value.trim(),phone:t,answers:B()};try{await T(r),e.style.display="none",x("You have successfully sent your answers!")}catch(l){u("Error: "+(((a=(s=l.response)==null?void 0:s.data)==null?void 0:a.message)||"Something went wrong. Please, try again!"))}finally{o&&(o.disabled=!1,o.textContent="Send")}})});
//# sourceMappingURL=index.js.map
