const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["assets/vendor-CbspLdtO.js","assets/vendor-CS74yUSC.css"])))=>i.map(i=>d[i]);
import{i as f,a as h,b as q}from"./assets/vendor-CbspLdtO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const S="modulepreload",L=function(e){return"/busy-status/"+e},y={},P=function(s,n,a){let t=Promise.resolve();if(n&&n.length>0){document.getElementsByTagName("link");const r=document.querySelector("meta[property=csp-nonce]"),i=(r==null?void 0:r.nonce)||(r==null?void 0:r.getAttribute("nonce"));t=Promise.allSettled(n.map(l=>{if(l=L(l),l in y)return;y[l]=!0;const p=l.endsWith(".css"),v=p?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${l}"]${v}`))return;const c=document.createElement("link");if(c.rel=p?"stylesheet":S,p||(c.as="script"),c.crossOrigin="",c.href=l,i&&c.setAttribute("nonce",i),document.head.appendChild(c),p)return new Promise((E,b)=>{c.addEventListener("load",E),c.addEventListener("error",()=>b(new Error(`Unable to preload CSS for ${l}`)))})}))}function o(r){const i=new Event("vite:preloadError",{cancelable:!0});if(i.payload=r,window.dispatchEvent(i),!i.defaultPrevented)throw r}return t.then(r=>{for(const i of r||[])i.status==="rejected"&&o(i.reason);return s().catch(o)})};function C(e){e?f(e,{initialCountry:"all",loadUtils:()=>P(()=>import("./assets/vendor-CbspLdtO.js").then(s=>s.u),__vite__mapDeps([0,1]))}):console.error("Елемент #phone не знайдено.")}const I="https://jsonplaceholder.typicode.com/posts",m=[{question:"Question 1",options:["option 1","option 2","option 3"]},{question:"Question 2",options:["option 1","option 2","option 3"]},{question:"Question 3",options:["option 1","option 2","option 3"]},{question:"Question 4",options:["option 1","option 2","option 3"]},{question:"Question 5",options:["option 1","option 2","option 3"]}];function O(e){h.success({position:"topRight",theme:"dark",messageColor:"white",backgroundColor:"#4CAF50",message:e})}function u(e){h.error({position:"topRight",theme:"dark",messageColor:"white",backgroundColor:"#ef4040",message:e})}let d=0,g=[];function w(){const e=document.getElementById("quiz"),n=m[d].options.map((t,o)=>`
        <li data-value="${t}">
          ${t}
        </li>
      `).join("");e.innerHTML=`
    <h2>${m[d].question}</h2>
    <ul class="options">
      ${n}
    </ul>
  `;const a=e.querySelectorAll(".options li");a.forEach(t=>{t.addEventListener("click",()=>{a.forEach(o=>o.classList.remove("selected")),t.classList.add("selected"),T()})}),$()}function T(){const e=document.querySelector(".options li.selected");e?(g.push(e.dataset.value),d++,d<m.length?w():(document.getElementById("quiz-container").style.display="none",document.getElementById("registration-container").style.display="block")):u("Please, choose an option")}function A(){return g}function $(){const e=document.getElementById("progress");e&&(e.innerHTML=`<span style="color: black;">${d+1}</span><span style="color: rgb(68, 67, 67);">/${m.length}</span>`)}async function B(e){return q.post(I,e,{headers:{"Content-Type":"application/json"}})}function Q(e){return/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(e)}function _(e,s){const n=e.querySelector("#name"),a=e.querySelector(".wt-email-input");return n.value.trim()?Q(a.value.trim())?!s||!f.getInstance(s).isValidNumber()?(u("Please, write a correct phone number!"),!1):!0:(u("Please, write a correct email"),!1):(u("Please, write your name"),!1)}document.addEventListener("DOMContentLoaded",()=>{w(),C(document.querySelector(".wt-phone-input"));const e=document.querySelector(".wt-form");e.addEventListener("submit",async s=>{var r,i;s.preventDefault();const n=document.getElementById("submitButton");if(n)n.disabled=!0,n.textContent="Sending...";else return;const a=document.querySelector(".wt-phone-input");if(!_(e,a)){n&&(n.disabled=!1,n.textContent="Send");return}const t=f.getInstance(a).getNumber(),o={name:e.querySelector("#name").value,email:e.querySelector(".wt-email-input").value.trim(),phone:t,answers:A()};try{await B(o),O("You have successfully sent your answers!"),document.getElementById("registration-container").innerHTML="<p>You have successfully sent your answers!</p>",e.reset()}catch(l){u("Error: "+(((i=(r=l.response)==null?void 0:r.data)==null?void 0:i.message)||"Something went wrong. Please, try again!"))}finally{n&&(n.disabled=!1,n.textContent="Send")}})});
//# sourceMappingURL=index.js.map
